### ISSUE TITLE
Two column component

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#205]
Request from Scott McLachlan to create two column content template for MCE to replace need for hard coding http://web.unimelb.edu.au/components/text/#two-columns

**Comment by yevek** [comment]
Have a text layout ready to deploy, just waiting for some CSS issues to be fixed.

https://github.com/unimelb/unimelb-design-system/issues/777

**Comment by timpw** [comment]
Hi Donna, just saw this. This is actually related to the request I was asking about on slack, so I'll just add here rather than create a new one. Scott's just asked me to submit a request about this two column option (I'm guessing he didn't know about this). But there's also some extra features he'd like (if possible).

Basically they'd like to be able to use this on pages like they have here, but make it something people without HTML knowledge can do. http://vca.unimelb.edu.au/engage/vca-film-and-television-50th-anniversary

Features they would like to include (if they are possible) are:
- have it behave like a listing, where child assets can be automatically pulled in
- have the images alternate sides with each item (or be able to choose the side)
- have the option for alt classes for each item (so that the background can alternate)
- have the option to add hero buttons for each item

**Comment by rhyslawry** [comment]
Definitely would like this
Would avoid having to hardcode:
```
<div class="half">
    <section></section>
    <section></section>
</div>
```
Which inexperienced editors often break.

At the very minimum just need two WYSIWYG boxes in the template, one for left side, one for right side, to be able to make things like:
![image](https://cloud.githubusercontent.com/assets/15081925/24936839/0c8ea2b8-1f70-11e7-85ae-26ef4e0eedec.png)

**Comment by dkevey** [comment]
Much awaited text layouts are now available. 
https://resources.web.unimelb.edu.au/controlled-environment/content-templates/figures-floating 
https://resources.web.unimelb.edu.au/controlled-environment/content-templates/two-columns
