### ISSUE TITLE
Page listing component not playing nicely with tabs

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/matrix-controlled-environment#259]
The "By category" page listing at the top of this page is showing the wrong contents - it's pulling in content from a different page listing component on the first tab (Home). Recaching fixes it, but only temporarily. It's weird because there are two other page listing components on the Projects tab which are displaying correctly.

Should be displaying like this:

![screen shot 2017-04-19 at 2 56 40 pm](https://cloud.githubusercontent.com/assets/11714609/25163834/6a29738a-2510-11e7-8981-db3b540683e5.png)

Instead displaying like this:

![screen shot 2017-04-19 at 2 56 03 pm](https://cloud.githubusercontent.com/assets/11714609/25163828/5c4aa8a6-2510-11e7-91a5-79552c33e2c5.png)

**Comment by dkevey** [comment]
Same issue on Grainger site ‘about’. Appears to be an issue where multiple listings are used in Tabbed Nav. Have narrowed it down to only being an issue when "multiple child assets" are used instead of a single parent asset. However seems to show inconsistant results between /_nocache /_recache and cached version. 

See http://grainger.unimelb.edu.au/#about
vs http://grainger.unimelb.edu.au/home/_recache#about

Have submitted a ticket to Squiz.

**Comment by dkevey** [comment]
Squiz have a fix for this in v5.3.5 - we have a major upgrade to v5.4.x scheduled for 5th June so we might have to wait for this.

**Comment by gyounger** [comment]
Ok thanks :)

**Comment by FPG-Github** [comment]
Hi Cam and Gav, this looks like it has been fixed with the last upgrade, can you check if the multiple listings within the tabs are working correctly for you guys - you may need to do an initial recahce but after that it should work.

**Comment by rothenburycam** [comment]
Looks like it's working for me - without a recache even. 🥇 

Will monitor - thanks Donna!

**Comment by gyounger** [comment]
Awesome, thanks heaps @dkevey!
