### ISSUE TITLE
Adjust "Header with image" template or offer home page template with smaller banner

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/matrix-controlled-environment#263]
It would be good to have a home page template which offered the reduced sized banner or adjust the "Header with image" template to accomodate home pages.

The problem with using "Header with image" for the homepage is that the breadcrumbs display the **Site Name** and **the home page title**. 

![screen shot 2017-05-24 at 1 48 50 pm](https://cloud.githubusercontent.com/assets/11714609/26386112/d25898ae-4087-11e7-9b80-5656be7af425.png)

A solution could be to have the breadcrumbs ignore type 2 assets in the same way that the hamburger menu does - or for Matrix to exclude it if it's the same as the home page defined under the globe asset.

**Comment by dkevey** [comment]
Hi @rothenburycam can you please include a link to the site - we have a few options already available for this

**Comment by rothenburycam** [comment]
https://cms.unimelb.edu.au/controlled-environment/smart-assam

@dkevey Here you are

**Comment by FPG-Github** [comment]
@dkevey & @rothenburycam Note: https://cms.unimelb.edu.au/controlled-environment/smart-assam is about to be launched under smartvillageslab.msd.unimelb.edu.au so that link will soon not work.

Also I have applied the Global - no hidden links in breadcrumbs design override to the home page to remove the "home" link in the breadcrumb. Can apply the same to the veil site unless there are better options.

**Comment by dkevey** [comment]
have applied Global - no hidden links in breadcrumbs (Id: #1500643) to veil home page as well - this is the best option for now.
