### ISSUE TITLE
Enable image only content template

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/matrix-controlled-environment#267]
The new image Text - Image floating component is super handy, but it would be good to have a variation of this that was for images only (i.e. no floating text). I've experimented with using this component for images only - which appears to work fine with no formatting issues/empty HTML tags. However, for a content maintainer, it might seem unintuitive/bad practice to use this component and leave the content field empty.

**Comment by dkevey** [comment]
Yes - this is not design for images only, and requires text. https://resources.web.unimelb.edu.au/controlled-environment/content-templates/figures-floating 

For general use with images, just inserting them onto the page is fine. I haven't seen any examples where people would want to use just images only with figure and caption that is not related to a story. 

I'll close this off for now unless you have good use cases that you can post as examples then feel free to reopen it.

**Comment by rothenburycam** [comment]
Here's an example: http://edsc.unimelb.edu.au/graduate/subject-options/msd-studios/architecture-studio-c-d-and-e/sm1-2017/semester-1-2017-studio-1

The benefit is that basic users can add a caption to an image without having to hard code.

**Comment by matrix-cms** [comment]
W have a “figure top” and “figure bottom” option on the figures floating – so this would be suitable in this instance.

https://resources.web.unimelb.edu.au/controlled-environment/content-templates/figures-floating

**Comment by rothenburycam** [comment]
Yep - that's what I was saying in my original comment. That works fine - but I thought it would be worth having an "Image only" option that removes the text field.

**Comment by dkevey** [comment]
I have considered an ‘image only’ layout, however there seem to be issues in Edit+ when too many content templates are loaded onto the page so we decided this was not a good idea.  I’ve reviewed a number of sites to check image issue and there doesn’t seem to be a real need for this, and in your example the existing template is the most suitable option. In the instance of the figure-top and figure bottom the content is area is optional and only prints the figure element and caption on the page – so technically this works as you suggest and in order to keep things simple and streamlined there is no justification for recreating this template as a stand-alone template.

**Comment by rothenburycam** [comment]
Sounds good to me - thank you Donna! 😌
