### ISSUE TITLE
"Text - Figure Floating" content template doesn't fit to Page templates with Aside content

### ISSUE THREAD

**Issue by timpw** [unimelb/matrix-controlled-environment#270]
#### Expected behaviour
When using the "Text - Figure Floating" content template on a page with an aside (Inside page with aside content, research page, etc.), both the text content and image would be expected to stay within the main content area.

#### Actual behaviour
Images hang out over the edges of the content. If set to float right, they overlap the Aside area. If floating left, they hang off the side of the browser window (and sometimes push the content down below)

![screen shot 2017-06-13 at 11 57 32 am](https://user-images.githubusercontent.com/21092709/27062755-945ad37e-5030-11e7-8078-a9b1928dcb77.png)
![screen shot 2017-06-13 at 11 58 41 am](https://user-images.githubusercontent.com/21092709/27062754-9457d1b0-5030-11e7-9be7-20d54bcaba0e.png)

#### Steps to reproduce
This seems to happen in all browsers, but the severity of the effect depends on the size of the browser window.

**Comment by dkevey** [comment]
Hi @timpw a couple of things here - the figures floating doesn't work with H2 styles inside the body copy (this is a bug that is/was open in the Design issues github). I also recommend that if you want to use the side bar layout that you change to just using the figures top/bottom rather than left/right. The left/right layout is really only suitable for single column page layouts.

**Comment by dkevey** [comment]
there are some changes to the figures floating in v7.0 so I will look at this shortly.

**Comment by dkevey** [comment]
Marking this as a duplicate as I think it will be solved with Figures floating text change #286
