### ISSUE TITLE
Allow <section> to be applied on Content Templates for padding

### ISSUE THREAD

**Issue by jporich** [unimelb/matrix-controlled-environment#274]
#### Expected behaviour
Various Content Templates work fantastic, however I've noticed a lot do not allow to be used in conjunction with the <section> tag when selecting Style Information. It would be good to be able to apply padding via the Edit/Admin interface rather than hard coding. 

This may not necessarily need to be a <section> tag specifically, but if if this property can be detected we may be able to apply padding directly to the div with inline-css?

![screen shot 2017-06-28 at 12 27 45 pm](https://user-images.githubusercontent.com/10070570/27618067-7d698d30-5bfd-11e7-9058-66fc2a2b5a50.png)

<img width="1406" alt="screen shot 2017-06-28 at 12 33 28 pm" src="https://user-images.githubusercontent.com/10070570/27618087-a5a9d958-5bfd-11e7-9453-17689d4f9abd.png">

![screen shot 2017-06-28 at 12 34 13 pm](https://user-images.githubusercontent.com/10070570/27618218-4f866248-5bfe-11e7-81c0-5e135fa123b2.png)

#### Actual behaviour
Templates leave very little padding before and after, adding a hard code <section> tag seems unnecessary to get an effect of nicer margins around content. Currently a <section> tag is inserted after the Content Template is applied in the Styling Information area of the CMS

#### Steps to reproduce
This seems to affect most Content Templates - accordion, page listing, two column layout etc.

**Comment by FPG-Github** [comment]
I would advice against this as it makes it hard to figure out what is going on as the extra tag generated by add Style information is not explicitly visible - also means that it is another place that needs to be updated if the templates or design change. We have had a litany of issue with people setting style information that is not compatible with the content, or changing content and not the style information or having to hunt around trying to figure out where the extra tag has come from.   

![hidden section tag](https://user-images.githubusercontent.com/4566277/27619592-ebc37102-5c06-11e7-8cc5-ec6205fce360.png)

**Comment by dkevey** [comment]
@jporich thanks for posting and I'm glad you have used the content templates enough to notice differences. There are a few items here that I'll address individually. 

**Container properties**
The first issue of not being able to change the presentation to section in the container properties is a known issue. As mentioned by Rachid, most editors do not even know how to use the container properties, and it does make it harder to troubleshoot. We have started adding in the section tag to CCT where we think is appropriate/suitable, however because there is great variation in how the CCT are used, which makes it hard to predict how to build them. 

I can see that the section tag of the accordion CCT is being printed out below (which is quite random) and I suspect something has probably changed in v5.4 as previously this wasn't printed (I'm pretty sure). 

So the simple fix here is to not set a property on the container itself.

**Accordion CCT**
RE: the spacing issue in the example above of the accordion. Usually it is best practice when using accordions to first describe what it is about which informs a user why they should click on each item.  We decided not to add additional styling options on the accordion CCT because there many scenarios where different styling can be applied to headings (left or center aligned) and how they are used. Text/heading above the CCT can be set using container properties to set section/div. I have also seen instances where 3 accordions have been stacked on top of each - which is not ideal - but we can't stop this from happening and it would look worse if there was a gap in between each one. 

**Styling CCT**
There are many ways to currently style CCT and one option would be to add multiple styling options in the CCT for people to select from, but this has an added overhead and we really need a designer to mandate what the options should be. I expect this will be resolved in the next version of the DDS when the new brand is rolled out, but we've tried to keep it simple and flexible for users. 

I would be interested to see more examples and gather peoples thoughts on how CCT are used, so that we can discuss how to make the next generation of CCT better.

**Comment by dkevey** [comment]
Actually going to close this one - as I've reviewed how the accordion is being used and we can't add in div wrapper without affecting current usage. Also Squiz have currently disabled the presentation field from use. Ideally all this stuff should be controlled within the CCT itself anyway. Will be reviewing this in the new CCT for the new DDS.
