### ISSUE TITLE
Authoriser and maintainer info required on site

### ISSUE THREAD

**Issue by dkevey** [unimelb/matrix-controlled-environment#8]
Authoriser and maintainer info needs to be added to metadata schema and parse file. 

![image](https://cloud.githubusercontent.com/assets/1305804/9432825/9f83493c-4a6c-11e5-805a-85f532816b30.png)

**Comment by yevek** [comment]
I'd still like to see this information included on every site somehow, even if it is in the comments section in the head of document. To do this however we would need to know the following for each site: 
- Owner name, department and email address
- Maintainer name and email address
In most cases we know main admin contacts for groups of sites, but due to editors changing over frequently it might be hard to keep updated.

**Comment by FPG-Github** [comment]
The templates used to contain that data and it was used in page footers. In the CMS I think owner information was part of the compulsory metadata, so pages couldn't be made live without. But it was never completed constantly or properly maintain and more then often become out of date when people left or moved on or structures changed, so not sure, in the end, that it was ever that useful over the longer term.

**Comment by dkevey** [comment]
I'm reopening this as I think this information is important and should be included for each site - at least in the page source so we can contact owners.

**Comment by dkevey** [comment]
closing this one - but when new DDS is rolled out it will be mandatory
