### ISSUE TITLE
Site root problems

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/matrix-controlled-environment#81]
Ben Kreunen raised this one.

Where you have a site with it's own Site asset, but which is designed to appear as part of a larger presence, the breadcrumbs and menu behave unexpectedly.

For example a 'Library' subsite like Special Collections: http://library.unimelb.edu.au/special-collections has no menu item, or breadcrumb link to go back to the Library site. Logically, it should appear as the top menu item, or home breadcrumb link, for these subsites to be seen as part of a greater whole.

Perhaps we could have an optional 'parent site' metadata field, which adjusted menu and breadcrumbs accordingly when a value was entered.

Fiddly, but could be done.

**Comment by yevek** [comment]
So in staff hub, for Faculty intranets they are hardcoding the first value (see second screenshot) and then generating the breadcrumbs as normal. So that individual site customisations are not required we would probably need an additional metadata_config field on the site globe to set the initial value. 

<img width="842" alt="staff-hub-breadcrumbs" src="https://cloud.githubusercontent.com/assets/1305804/16141478/67415988-349f-11e6-8dc7-49b464845ce5.png">

<img width="933" alt="faculty-breadcrumbs" src="https://cloud.githubusercontent.com/assets/1305804/16141480/72a69f18-349f-11e6-961c-7e5ed2cfc625.png">
